### PR TITLE
Update package.json for new resin-semver release

### PR DESCRIPTION
**Pull request by pdcastro**
This repo is one of the 16 repos identified to use/require a [resin-semver](https://github.com/resin-io-modules/resin-semver) version older than 1.4.0. See also:
* [Trello card](https://trello.com/c/11ZJfEv6/114-update-repos-that-depend-on-resin-semver)
* [Flowdock thread](https://www.flowdock.com/app/rulemotion/namechange/threads/lS-o4xF4qMvf-o2rAtdrqaZEPhs)

### CODE REVIEW

**Comment by telphan** [comment]
@pdcastro Why are we updating this package?

**Comment by pdcastro** [comment]
@telphan, thanks for looking into this PR  :) 
Why update this package? It's not about this package specifically, but Petros asked me to update packages that make use of `resin-semver`, to bump the required version to 1.4.0. I found 16 such packages -- see [Trello card](https://trello.com/c/11ZJfEv6/114-update-repos-that-depend-on-resin-semver) and [Flowdock thread](https://www.flowdock.com/app/rulemotion/namechange/threads/lS-o4xF4qMvf-o2rAtdrqaZEPhs). If this package doesn't need to be updated, just let me know!

**Comment by telphan** [comment]
I see. thanks for the explanation?

**Comment by telphan** [comment]
@resin-jenkins retest this please

**Comment by telphan** [comment]
@resin-jenkins retest this please

**Pull request merged**
